version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: plcnext_db
    environment:
      - POSTGRES_DB=plcnext_data
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: